server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/jobhunter
    username: jobhunter
    password: jobhunter

  jpa:
    show-sql: false

management:
  endpoint:
    health:
      show-details: always

jobhunter:
  auth0:
    enabled: false
