server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/jobhunter
    username: jobhunter
    password: jobhunter

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always

jobhunter:
  auth0:
    enabled: false

logging:
  level:
    com.mshykhov.jobhunter: DEBUG
    org.springframework.web: DEBUG
